spring.application.name=capstone-project
# Hyperledger Fabric configuration
fabric.mspid=Org1MSP
fabric.channel=mychannel
fabric.chaincode=integritycc
fabric.peer.endpoint=localhost:7051
fabric.peer.override-auth=peer0.org1.example.com
fabric.crypto.cert-dir-path=C:/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts
fabric.crypto.key-dir-path=C:/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore
fabric.crypto.tls-cert-path=C:/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt

# Database Connection Properties
spring.datasource.url=jdbc:mysql://localhost:3306/offchaindB
spring.datasource.username=myuser
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG

