spring.application.name=capstone-project
# Hyperledger Fabric configuration
fabric.wallet-path=wallet
fabric.user=appUser
fabric.network-config-path=connection.json
fabric.channel=mychannel
fabric.chaincode=integritycc
