package com.mp.capstone.project.mapper;

import com.mp.capstone.project.dto.request.EmployeeRequestDTO;
import com.mp.capstone.project.dto.response.EmployeeResponseDTO;
import com.mp.capstone.project.entity.Employee;
import com.mp.capstone.project.entity.MedicalRecord;
import com.mp.capstone.project.entity.Patient;
import org.springframework.stereotype.Component;

import java.util.stream.Collectors;

@Component
public class EmployeeMapper {

    /**
     * Converts an Employee entity to an EmployeeResponseDTO.
     * Patient and MedicalRecord relationships are flattened to ID sets.
     */
    public EmployeeResponseDTO toResponseDTO(Employee employee) {
        if (employee == null) return null;

        return new EmployeeResponseDTO(
                employee.getId(),
                employee.getName(),
                employee.getRole(),
                employee.getGender(),
                employee.getReligion(),
                employee.getDob(),
                employee.getPatients()
                        .stream()
                        .map(Patient::getTrn)
                        .collect(Collectors.toSet()),
                employee.getRecords()
                        .stream()
                        .map(MedicalRecord::getId)
                        .collect(Collectors.toSet())
        );
    }

    /**
     * Converts an EmployeeRequestDTO to a new Employee entity.
     * ID is generated by JPA (@GeneratedValue); relationships are managed separately.
     */
    public Employee toEntity(EmployeeRequestDTO dto) {
        if (dto == null) return null;

        Employee emp = new Employee();
        emp.setName(dto.getName());
        emp.setRole(dto.getRole());
        emp.setGender(dto.getGender());
        emp.setReligion(dto.getReligion());
        emp.setDob(dto.getDob());
        return emp;
    }

    /**
     * Applies EmployeeRequestDTO fields onto an existing managed Employee entity.
     * Used for PUT (update) operations.
     */
    public void updateEntityFromDTO(EmployeeRequestDTO dto, Employee employee) {
        employee.setName(dto.getName());
        employee.setRole(dto.getRole());
        employee.setGender(dto.getGender());
        employee.setReligion(dto.getReligion());
        employee.setDob(dto.getDob());
    }
}
